#!/usr/bin/env zsh

# Custom theme configuration
OS_TYPE=$(uname)

# command time & prompt time
DISABLE_ZSH_COMMAND_TIME_MSG=true

AGNOSTERZAK_COMMAND_EXECUTION_TIME=true
AGNOSTERZAK_COMMAND_EXECUTION_TIME_THRESHOLD=3

AGNOSTERZAK_PROMPT_TIME=false
AGNOSTERZAK_PROMPT_TIME_THRESHOLD=5

# git
AGNOSTERZAK_GIT_SHOW_CHANGESET=true
AGNOSTERZAK_GIT_CHANGESET_HASH_LENGTH=6

if [[ $OS_TYPE =~ "MSYS_NT" || $OS_TYPE =~ "MINGW" || $OS_TYPE =~ "CYGWIN_NT" ]]; then
    AGNOSTERZAK_GIT_SHOW_STASH=false
    AGNOSTERZAK_GIT_SHOW_TAGS=false
    AGNOSTERZAK_GIT_SHOW_UPSTREAM=false
else
    AGNOSTERZAK_GIT_SHOW_STASH=true
    AGNOSTERZAK_GIT_SHOW_TAGS=true
    AGNOSTERZAK_GIT_SHOW_UPSTREAM=true
fi
